version: '3.4'
services:
    if3250_2022_01_buletin_backend:
        image: if3250_2022_01_buletin_backend:latest
        depends_on:
            - database
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:80'
        environment:
            - connection-string=Host=database;Username=postgres;Password=postgres;Database=buletin.id;
    database:
        image: postgres:latest
        environment:
            - POSTGRES_DB=buletin.id
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        restart: unless-stopped
        volumes:
            - database-data:/var/lib/postgresql/data/

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - '5050:80'
        restart: unless-stopped
        volumes:
            - pgadmin:/root/.pgadmin

volumes:
    database-data:
    pgadmin:
